modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="blocklings"
version="${file.jarVersion}"
displayName="Blocklings"
displayURL="https://www.curseforge.com/minecraft/mc-mods/blocklings"
logoFile="blocklings.png"
credits="WillR27"
authors="WillR27"
description='''
This mod adds small, block-like creatures into your world. They can then be tamed and are able to perform different tasks for you in the world, as well as gain experience and level up. For example, your blockling will be able to guard you from evil creatures at night, go mining with you deep underground, chop away at trees as well as plant and harvest crops.
'''

[[dependencies.blocklings]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.blocklings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
